### ISSUE TITLE
femboy.hu is down

### ISSUE THREAD

**Issue by Godeps2891** [hnhx/website#8]
the site now redirects to dynu.com is this a temporary problem or is the site down for good?

**Comment by kxrn0** [comment]
it's over

**Comment by hnhx** [comment]
Hey, I have a new homeserver and I didn't really make it public yet, I'm not sure if I ever will since both my tor instances and my clearnet instances were ddosed multiple times so yeah. Thats what i get for hosting stuff and making libre software i guess kek
